version: '2'
services:
  web:
    build: ./
    labels:
       - "traefik.docker.network=web"
       - "traefik.enable=true"
       - "traefik.http.routers.website.rule=Host(`shoevault.io`)"
       - "traefik.http.routers.website.entrypoints=websecure"
       - "traefik.http.routers.website.tls.certresolver=myresolver"
       - "traefik.http.services.website.loadbalancer.server.port=80"
    environment:
       - ALLOW_OVERRIDE=true
       - APACHE_DOCUMENT_ROOT=/var/www/html
    volumes:
       - ./public:/var/www/html
       - ./node_modules:/var/www/data
    networks:
       - web
       - default
networks:
  web:
    external: true
